Pivot Tables

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "Date": pd.date_range("2023-01-01", periods=20),
    "Product": ["A", "B", "C", "D"] * 5,
    "Region": [
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
    ],
    "Sales": np.random.randint(100, 1000, 20),
    "Units": np.random.randint(10, 100, 20),
    "Rep": [
        "John",
        "Mary",
        "Bob",
        "Alice",
        "John",
        "Mary",
        "Bob",
        "Alice",
        "John",
        "Mary",
        "Bob",
        "Alice",
        "John",
        "Mary",
        "Bob",
        "Alice",
        "John",
        "Mary",
        "Bob",
        "Alice",
    ],
}

df = pd.DataFrame(data)

df["Month"] = df["Date"].dt.month_name()
df["Quarter"] = "Q" + df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    150     54   John  January      Q1
1  2023-01-02       B   West    909     62   Mary  January      Q1
2  2023-01-03       C  North    822     65    Bob  January      Q1
3  2023-01-04       D  South    558     26  Alice  January      Q1
4  2023-01-05       A   East    152     46   John  January      Q1
5  2023-01-06       B   West    654     25   Mary  January      Q1
6  2023-01-07       C  North    947     88    Bob  January      Q1
7  2023-01-08       D  South    870     51  Alice  January      Q1
8  2023-01-09       A   East    898     63   John  January      Q1
9  2023-01-10       B   West    828     74   Mary  January      Q1
10 2023-01-11       C  North    323     38    Bob  January      Q1
11 2023-01-12       D  South    932     33  Alice  January      Q1
12 2023-01-13       A   East    231     45   John  January      Q1
13 2023-01-14       B   West    886     19   Mary  January      Q1
14 2023-01-15       C  North    467     41    Bob  January      Q1
15 2023-01-16       D  South    549     51  Alice  January      Q1
16 2023-01-17       A   East    540     23   John  January      Q1
17 2023-01-18       B   West    360     13   Mary  January      Q1
18 2023-01-19       C  North    692     84    Bob  January      Q1
19 2023-01-20       D  South    100     60  Alice  January      Q1

In [3]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product')

Product      A      B      C      D
Region
East     394.2    NaN    NaN    NaN
North      NaN    NaN  650.2    NaN
South      NaN    NaN    NaN  601.8
West       NaN  727.4    NaN    NaN

In [4]:
pd.pivot_table(df, values="Sales", index="Region", columns="Product", aggfunc='median')

Product      A      B      C      D
Region
East     231.0    NaN    NaN    NaN
North      NaN    NaN  692.0    NaN
South      NaN    NaN    NaN  558.0
West       NaN  828.0    NaN    NaN

In [5]:
pd.pivot_table(df, values=["Sales", "Units"], index="Region", columns="Product")

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     394.2    NaN    NaN    NaN  46.2   NaN   NaN   NaN
North      NaN    NaN  650.2    NaN   NaN   NaN  63.2   NaN
South      NaN    NaN    NaN  601.8   NaN   NaN   NaN  44.2
West       NaN  727.4    NaN    NaN   NaN  38.6   NaN   NaN

Cross Tabs

In [6]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0